const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
function toast(msg,type="success"){let t=document.getElementById("toast");if(!t)return;t.textContent=(type==="success"?"✓ ":"⚠ ")+msg;t.className="show "+type;clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.className="",3200)}
function togglePass(id){let e=document.getElementById(id);e.type=e.type==="password"?"text":"password"}
function getUsers(){return JSON.parse(localStorage.getItem("ever_users")||"[]")}
function currentUser(){return JSON.parse(localStorage.getItem("ever_current")||"null")}
function requireAuth(){if(!currentUser()){location.href="login.html";return false}return true}
function updateAuthLinks(){const el=document.getElementById("authLinks");if(!el)return;const u=currentUser();el.innerHTML=u?`<a class="btn ghost" href="dashboard.html">Dashboard</a><button class="btn" id="logoutNav">Logout</button>`:`<a class="btn ghost" href="login.html">Login</a><a class="btn" href="signup.html">Sign Up</a>`;document.getElementById("logoutNav")?.addEventListener("click",()=>{localStorage.removeItem("ever_current");location.reload()})}
function renderServices(id="serviceGrid"){const g=document.getElementById(id);if(!g||!window.SERVICES)return;g.innerHTML=SERVICES.map(s=>`<article class="service-card reveal"><div class="service-icon">${s.icon}</div><h3>${s.name}</h3><p>${s.desc}</p><strong>${money(s.price)}</strong><a class="text-link" href="booking.html">Add in booking →</a></article>`).join("")}
function renderVenues(){const g=document.getElementById("venueGrid");if(!g)return;let arr=[...VENUES],q=(document.getElementById("venueSearch")?.value||"").toLowerCase(),sort=document.getElementById("venueSort")?.value||"featured";arr=arr.filter(v=>(v.name+" "+v.loc).toLowerCase().includes(q));if(sort==="low")arr.sort((a,b)=>a.price-b.price);if(sort==="high")arr.sort((a,b)=>b.price-a.price);if(sort==="rating")arr.sort((a,b)=>b.rating-a.rating);g.innerHTML=arr.map(v=>`<article class="venue-card reveal"><div class="venue-image"><span>${v.img}</span><small>${v.tag}</small></div><div class="venue-body"><div><h3>${v.name}</h3><p>📍 ${v.loc}</p></div><div class="venue-meta"><span>★ ${v.rating}</span><span>👥 ${v.cap}</span></div><div class="venue-bottom"><strong>${money(v.price)}</strong><button class="btn small" onclick="chooseVenue(${v.id})">Choose</button></div></div></article>`).join("")}
function chooseVenue(id){localStorage.setItem("ever_venue",id);toast("Venue selected. Continue to booking.");setTimeout(()=>location.href="booking.html",500)}
function renderPackages(){const g=document.getElementById("packageGrid");if(!g)return;g.innerHTML=PACKAGES.map((p,i)=>`<article class="package-card ${i===1?"featured":""} reveal">${i===1?'<span class="popular">MOST POPULAR</span>':""}<p class="eyebrow">${p.tag}</p><h3>${p.name}</h3><div class="pkg-price">${money(p.price)}</div><ul>${p.features.map(x=>`<li>✓ ${x}</li>`).join("")}</ul><a class="btn ${i===1?"":"ghost"}" href="booking.html">Choose ${p.name}</a></article>`).join("")}
function modalOpen(html){const m=document.getElementById("modal");if(!m)return;document.getElementById("modalContent").innerHTML=html;m.classList.add("open")}
document.addEventListener("DOMContentLoaded",()=>{updateAuthLinks();renderServices();renderVenues();renderPackages();document.getElementById("venueSearch")?.addEventListener("input",renderVenues);document.getElementById("venueSort")?.addEventListener("change",renderVenues);document.querySelectorAll(".modal-close").forEach(x=>x.onclick=()=>x.closest(".modal").classList.remove("open"));document.getElementById("menuBtn")?.addEventListener("click",()=>document.getElementById("nav")?.classList.toggle("open"));document.getElementById("contactForm")?.addEventListener("submit",e=>{e.preventDefault();e.target.reset();toast("Message sent successfully! We'll be in touch.")});document.querySelectorAll("[data-count]").forEach(el=>{let target=+el.dataset.count,start=0,step=Math.max(1,Math.ceil(target/50));let tm=setInterval(()=>{start+=step;if(start>=target){start=target;clearInterval(tm)}el.textContent=start+"+"},25)});let minDate=new Date();minDate.setDate(minDate.getDate()+1);document.getElementById("date")?.setAttribute("min",minDate.toISOString().split("T")[0]);let target=new Date();target.setDate(target.getDate()+120);function tick(){let d=target-new Date();if(d<0)d=0;document.getElementById("days")&&(document.getElementById("days").textContent=Math.floor(d/86400000));document.getElementById("hours")&&(document.getElementById("hours").textContent=String(Math.floor(d%86400000/3600000)).padStart(2,"0"));document.getElementById("mins")&&(document.getElementById("mins").textContent=String(Math.floor(d%3600000/60000)).padStart(2,"0"));document.getElementById("secs")&&(document.getElementById("secs").textContent=String(Math.floor(d%60000/1000)).padStart(2,"0"))}tick();setInterval(tick,1000);setTimeout(()=>document.getElementById("loader")?.classList.add("hide"),500);document.querySelectorAll(".reveal").forEach(x=>x.classList.add("visible"));document.getElementById("logout")?.addEventListener("click",()=>{localStorage.removeItem("ever_current");location.href="index.html"})})
