let step=1, selected={venueId:Number(localStorage.getItem("ever_venue"))||null,packageId:null,services:[]};
document.addEventListener("DOMContentLoaded",()=>{if(!requireAuth())return;let u=currentUser();bName.value=u.name;bEmail.value=u.email;bPhone.value=u.phone||"";renderBookingChoices();updatePrice();showStep();next.onclick=()=>{if(validateStep()){if(step<6){step++;showStep()}else{} }};prev.onclick=()=>{if(step>1){step--;showStep()}};bookingForm.addEventListener("submit",e=>{e.preventDefault();if(step!==6)return;let total=calc();let booking={id:"EA-"+String(Date.now()).slice(-7),created:Date.now(),email:u.email,name:bName.value,date:date.value,guests:+guests.value,type:type.value,venueId:selected.venueId,packageId:selected.packageId,services:selected.services,total};let arr=JSON.parse(localStorage.getItem("ever_bookings")||"[]");arr.push(booking);localStorage.setItem("ever_bookings",JSON.stringify(arr));document.getElementById("bookingTicket").innerHTML=`<div class="ticket"><p><b>Booking ID</b><span>${booking.id}</span></p><p><b>Name</b><span>${booking.name}</span></p><p><b>Date</b><span>${new Date(booking.date).toLocaleDateString("en-IN")}</span></p><p><b>Venue</b><span>${VENUES.find(v=>v.id===booking.venueId)?.name}</span></p><p><b>Package</b><span>${PACKAGES.find(p=>p.id===booking.packageId)?.name}</span></p><p><b>Estimated Cost</b><span>${money(booking.total)}</span></p></div>`;successModal.classList.add("open")})});
function renderBookingChoices(){bookingVenues.innerHTML=VENUES.map(v=>`<div class="choice ${selected.venueId===v.id?"selected":""}" data-v="${v.id}" onclick="selectVenue(${v.id})"><div class="choice-icon">${v.img}</div><div><b>${v.name}</b><small>${v.loc} · ${v.cap} guests</small></div><strong>${money(v.price)}</strong></div>`).join("");bookingPackages.innerHTML=PACKAGES.map(p=>`<div class="choice ${selected.packageId===p.id?"selected":""}" onclick="selectPackage(${p.id})"><div><b>${p.name}</b><small>${p.tag} · ${p.features.slice(0,2).join(" · ")}</small></div><strong>${money(p.price)}</strong></div>`).join("");bookingServices.innerHTML=SERVICES.map(s=>`<div class="choice ${selected.services.includes(s.id)?"selected":""}" onclick="toggleService(${s.id})"><div class="choice-icon">${s.icon}</div><div><b>${s.name}</b><small>${s.desc}</small></div><strong>${money(s.price)}</strong></div>`).join("")}
function selectVenue(id){selected.venueId=id;localStorage.setItem("ever_venue",id);renderBookingChoices();updatePrice()}
function selectPackage(id){selected.packageId=id;renderBookingChoices();updatePrice()}
function toggleService(id){selected.services=selected.services.includes(id)?selected.services.filter(x=>x!==id):[...selected.services,id];renderBookingChoices();updatePrice()}
function calc(){let v=VENUES.find(x=>x.id===selected.venueId),p=PACKAGES.find(x=>x.id===selected.packageId),guest=(+guests.value||0)*500,s=selected.services.reduce((a,id)=>a+(SERVICES.find(x=>x.id===id)?.price||0),0);return (v?.price||0)+(p?.price||0)+guest+s}
function updatePrice(){let v=VENUES.find(x=>x.id===selected.venueId),p=PACKAGES.find(x=>x.id===selected.packageId),gc=(+guests?.value||0)*500,sc=selected.services.reduce((a,id)=>a+(SERVICES.find(x=>x.id===id)?.price||0),0),total=(v?.price||0)+(p?.price||0)+gc+sc;venueCost.textContent=money(v?.price);packageCost.textContent=money(p?.price);guestCost.textContent=money(gc);serviceCost.textContent=money(sc);total.textContent=money(total);totalSmall.textContent=money(total);guests?.addEventListener("input",updatePrice,{once:true})}
function validateStep(){if(step===1)return bookingForm.reportValidity();if(step===2)return bookingForm.reportValidity();if(step===3&&!selected.venueId){toast("Please choose a venue","error");return false}if(step===4&&!selected.packageId){toast("Please choose a package","error");return false}if(step===6)return true;if(step===5){review.innerHTML=`<div class="review-list"><p><b>Name</b>${bName.value}</p><p><b>Date</b>${new Date(date.value).toLocaleDateString("en-IN")}</p><p><b>Guests</b>${guests.value}</p><p><b>Venue</b>${VENUES.find(v=>v.id===selected.venueId)?.name}</p><p><b>Package</b>${PACKAGES.find(p=>p.id===selected.packageId)?.name}</p><p><b>Services</b>${selected.services.map(id=>SERVICES.find(s=>s.id===id)?.name).join(", ")||"None"}</p><p><b>Estimated Total</b>${money(calc())}</p></div>`}return true}
function showStep(){document.querySelectorAll(".step").forEach(x=>x.classList.toggle("active",+x.dataset.step===step));document.querySelectorAll(".stepper span").forEach((x,i)=>x.classList.toggle("active",i+1===step));prev.classList.toggle("hidden",step===1);next.classList.toggle("hidden",step===6);confirm.classList.toggle("hidden",step!==6);if(step===6)validateStep()}
